// D4/W4 — composite real business names onto the AI-generated (premium-tier)
// buildings' blank ground-floor fascia, in place, over assets/shopfronts/
// elevations/b<buildingIndex>.jpg.
//
//   node scripts/apply-signage.mjs
//
// Why not let the AI paint the text: it misspells real Leith Walk business
// names (Dan's flag), so scripts/gen-facade-elevations.mjs prompts for a
// completely BLANK dark fascia band and this script draws the real name on
// top afterward — same "accurate name over accurate-as-we-can-get imagery"
// policy the old buildNameAtlas placeholder system used, reused here as an
// OVERLAY instead of a whole-building substitute.
//
// Inputs (committed, not regenerated by this script):
//   assets/shopfronts/signage-names.json  — every unique business name that
//     needs a fascia (order is the tile order below).
//   assets/shopfronts/signage-atlas.jpg   — one 128x64px tile per name, 16
//     cols, in signage-names.json's order. SAME drawTile visual design as
//     src/placeholders.js's buildNameAtlas (dark stone frame, fascia board,
//     centred name) — duplicated here rather than imported because this atlas
//     was built ONCE by hand (see recipe below), not at every page load like
//     the in-engine placeholder atlas still is for buildings with no photo
//     AND no AI elevation (shouldn't exist after W3, but the engine keeps the
//     fallback for safety).
//
//   RECIPE (only needed if signage-names.json changes — e.g. a manifest
//   rebuild finds new businesses): open the running dev server, dismiss the
//   title card, then in the browser console run the drawTile+buildNameAtlas
//   logic from src/placeholders.js against the new name list at TILE_W=128,
//   TILE_H=64, COLS=16 (half src/placeholders.js's normal 256x128 — this
//   atlas only ever gets scaled onto a photo, not sampled at native size),
//   canvas.toDataURL('image/jpeg', 0.8), and save the result over
//   assets/shopfronts/signage-atlas.jpg. The oversized string is auto-saved
//   to a tool-results file by the harness — decode its base64 with Node/
//   Python rather than pasting it through chat.
//
// Ground-band assumption: an AI elevation has no vision-detected groundFrac
// (unlike a real photo), so this assumes uniform storey rhythm — the bottom
// 1/storeys fraction of the image is the ground floor, matching what
// gen-facade-elevations.mjs's prompt asked FLUX for.

import { readFileSync, existsSync, mkdirSync } from 'fs';
import { execFileSync } from 'child_process';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const shopDir = join(root, 'assets/shopfronts');
const elevDir = join(shopDir, 'elevations');
const tmpDir = join(shopDir, '.signage-tmp');

const TILE_W = 128, TILE_H = 64, COLS = 16;
const MIN_UNIT_PX = 80;  // below this a name is illegible — drop businesses rather than crush them
const MAX_UNITS = 6;

const manifest = JSON.parse(readFileSync(join(shopDir, 'manifest.json'), 'utf8'));
const elev = JSON.parse(readFileSync(join(shopDir, 'elevations.json'), 'utf8'));
const names = JSON.parse(readFileSync(join(shopDir, 'signage-names.json'), 'utf8'));
const nameIndex = new Map(names.map((n, i) => [n, i]));
// D4.1/W2 — a handmade elevation already carries real, photographed
// signage; overlaying the name atlas on top would double it up.
const handmadePath = join(shopDir, 'handmade.json');
const handmade = existsSync(handmadePath) ? JSON.parse(readFileSync(handmadePath, 'utf8')) : {};

const genByBuilding = new Map(elev.elevations.filter((e) => e.generated).map((e) => [e.buildingIndex, e]));

function probe(file) {
  const out = execFileSync('ffprobe', ['-v', 'error', '-select_streams', 'v:0',
    '-show_entries', 'stream=width,height', '-of', 'csv=p=0', file]).toString().trim();
  const [w, h] = out.split(',').map(Number);
  return { w, h };
}

mkdirSync(tmpDir, { recursive: true });

let done = 0, skippedNoElev = 0, skippedNarrow = 0;
const missingNames = new Set();

for (const b of manifest.buildings) {
  if (b.placedSlug || !b.businesses.length || handmade[b.buildingIndex]) continue;
  const g = genByBuilding.get(b.buildingIndex);
  if (!g || g.tier !== 'premium') { skippedNoElev++; continue; }
  const imgPath = join(elevDir, `b${b.buildingIndex}.jpg`);
  if (!existsSync(imgPath)) { skippedNoElev++; continue; }

  const { w: imgW, h: imgH } = probe(imgPath);
  const groundH = Math.round(imgH / g.storeys);
  const groundY = imgH - groundH;

  // Only businesses with an atlas tile count toward the unit layout — decide
  // this FIRST so the filter-graph loop below never has to skip mid-chain.
  const usableBiz = b.businesses
    .filter((biz) => { const has = nameIndex.has(biz.name); if (!has) missingNames.add(biz.name); return has; })
    .slice(0, MAX_UNITS);
  const n = Math.min(usableBiz.length, Math.floor(imgW / MIN_UNIT_PX));
  if (n < 1) { skippedNarrow++; continue; }
  const unitW = Math.floor(imgW / n);

  const inputs = ['-i', imgPath];
  let filter = '';
  let lastLabel = '0:v';
  for (let k = 0; k < n; k++) {
    const idx = nameIndex.get(usableBiz[k].name);
    const col = idx % COLS, row = Math.floor(idx / COLS);
    const ffmpegInputIndex = inputs.length / 2; // 0=imgPath, 1=first atlas ref, ...
    inputs.push('-i', join(shopDir, 'signage-atlas.jpg'));
    const cropped = `crop${k}`, scaled = `s${k}`;
    filter += `[${ffmpegInputIndex}:v]crop=${TILE_W}:${TILE_H}:${col * TILE_W}:${row * TILE_H}[${cropped}];`;
    filter += `[${cropped}]scale=${unitW}:${groundH}:flags=lanczos[${scaled}];`;
    const outLabel = k === n - 1 ? 'v' : `m${k}`;
    filter += `[${lastLabel}][${scaled}]overlay=${k * unitW}:${groundY}[${outLabel}];`;
    lastLabel = outLabel;
  }

  const tmpOut = join(tmpDir, `b${b.buildingIndex}.jpg`);
  execFileSync('ffmpeg', ['-loglevel', 'error', '-y', ...inputs,
    '-filter_complex', filter.slice(0, -1), '-map', '[v]', '-frames:v', '1', '-q:v', '3', tmpOut]);
  // Re-grade the composited signage strip is unnecessary — the atlas tiles
  // are already dark/desaturated to match; overwrite in place.
  execFileSync('mv', [tmpOut, imgPath]);
  done++;
}

execFileSync('rm', ['-rf', tmpDir]);

console.log(`signage applied to ${done} buildings.`);
console.log(`  ${skippedNoElev} skipped (no premium AI elevation yet — run gen-facade-elevations.mjs first)`);
console.log(`  ${skippedNarrow} skipped (too narrow for a legible unit)`);
if (missingNames.size) console.log(`  ${missingNames.size} business name(s) not in signage-atlas.jpg — rebuild it (see recipe in this file's header): ${[...missingNames].slice(0, 10).join('; ')}${missingNames.size > 10 ? '…' : ''}`);
